version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: carlist_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carlist
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: carlist_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: carlist_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
